apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: german-practice-web
  labels:
    app: german-practice-web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: german-practice-web
    spec:
      containers:
        - name: german-practice-web
          image: gcr.io/german-practice/german-practice-web:0.0.10
          imagePullPolicy: Always
          ports:
          - containerPort: 5000

