kind: Service
apiVersion: v1
metadata:
  name: german-practice-web-service
spec:
  selector:
    app: german-practice-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
